name: Build

on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Build project
      run: echo "Build step here"
